### ISSUE TITLE
Papers on Unit testing and RegEx generation

### ISSUE THREAD

**Issue by lsiddiqsunny** [gai4se/LLM4SE#15]
Would you add the following papers:

1. [Using Large Language Models to Generate JUnit Tests: An Empirical Study ](https://s2e-lab.github.io/preprints/ease24-preprint.pdf) - EASE'2024
2. [Understanding Regular Expression Denial of Service (ReDoS): Insights from LLM-Generated Regexes and Developer Forums  ](https://s2e-lab.github.io/preprints/icpc24-preprint.pdf) - ICPC'2024
3. [Re(gEx|DoS)Eval: Evaluating Generated Regular Expressions and their Proneness to DoS Attacks](https://s2e-lab.github.io/preprints/msr_mining_challenge24-preprint.pdf) - ICSE-NIER'2024

**Comment by maxxbw54** [comment]
added. thanks.
